"""
Document Generation Module for Nitro AI
========================================

Generate professional documents: PDF reports, PowerPoint presentations, and text files.
LIGHTWEIGHT - Uses minimal dependencies perfect for low-compute laptops.

FEATURES:
- PDF generation (reports, documents)
- PowerPoint presentations (PPTX)
- Text document generation
- Template system
- Export/download support

DEPENDENCIES (Lightweight):
- reportlab (PDF) - 2MB
- python-pptx (PowerPoint) - 1MB
- No heavy ML models needed!

FUTURE ENHANCEMENTS:
- AI-generated content
- Custom templates
- Image embedding
- Charts and graphs
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import json

# PDF Generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("⚠️  ReportLab not installed. PDF generation will return placeholders.")
    print("   Install with: pip install reportlab")

# PowerPoint Generation
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN
    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False
    print("⚠️  python-pptx not installed. PowerPoint generation will return placeholders.")
    print("   Install with: pip install python-pptx")


class DocumentGenerator:
    """
    Professional document generation for Nitro AI.
    
    BEGINNER-FRIENDLY:
    - Simple API
    - Clear examples
    - Minimal dependencies
    - Good for learning!
    """
    
    def __init__(self, output_dir: str = "../documents"):
        """
        Initialize document generator.
        
        Args:
            output_dir: Where to save generated documents
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Track generated documents
        self.generated_docs = []
    
    # ========================================================================
    # PDF GENERATION
    # ========================================================================
    
    def generate_pdf(
        self,
        title: str,
        content: str,
        author: str = "Nitro AI",
        filename: Optional[str] = None
    ) -> Dict:
        """
        Generate a professional PDF document.
        
        Args:
            title: Document title
            content: Main content (can include multiple paragraphs)
            author: Author name
            filename: Custom filename (optional)
            
        Returns:
            Dictionary with document info and file path
            
        Example:
            >>> doc_gen = DocumentGenerator()
            >>> result = doc_gen.generate_pdf(
            ...     title="My Report",
            ...     content="This is the content\\n\\nMultiple paragraphs work!",
            ...     author="John Doe"
            ... )
            >>> print(result['file_path'])
        """
        if not REPORTLAB_AVAILABLE:
            return self._placeholder_response("PDF", title)
        
        try:
            # Generate filename
            if not filename:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"{title.replace(' ', '_')}_{timestamp}.pdf"
            
            file_path = self.output_dir / filename
            
            # Create PDF
            doc = SimpleDocTemplate(
                str(file_path),
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Build content
            story = []
            styles = getSampleStyleSheet()
            
            # Title
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#667eea'),
                spaceAfter=30,
                alignment=1  # Center
            )
            story.append(Paragraph(title, title_style))
            story.append(Spacer(1, 12))
            
            # Metadata
            meta_style = styles['Normal']
            story.append(Paragraph(f"<b>Author:</b> {author}", meta_style))
            story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", meta_style))
            story.append(Paragraph(f"<b>Generated by:</b> Nitro AI", meta_style))
            story.append(Spacer(1, 20))
            
            # Separator line
            story.append(Spacer(1, 12))
            
            # Content
            content_style = styles['BodyText']
            paragraphs = content.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    story.append(Paragraph(para, content_style))
                    story.append(Spacer(1, 12))
            
            # Build PDF
            doc.build(story)
            
            # Track generated document
            doc_info = {
                'type': 'PDF',
                'title': title,
                'author': author,
                'filename': filename,
                'file_path': str(file_path),
                'size_bytes': file_path.stat().st_size,
                'generated_at': datetime.now().isoformat(),
                'status': 'completed'
            }
            
            self.generated_docs.append(doc_info)
            return doc_info
            
        except Exception as e:
            return {
                'type': 'PDF',
                'title': title,
                'status': 'error',
                'error': str(e),
                'message': 'Failed to generate PDF. Check logs.'
            }
    
    # ========================================================================
    # POWERPOINT GENERATION
    # ========================================================================
    
    def generate_ppt(
        self,
        title: str,
        slides: List[Dict],
        filename: Optional[str] = None
    ) -> Dict:
        """
        Generate a PowerPoint presentation.
        
        Args:
            title: Presentation title
            slides: List of slide dictionaries
                Each slide: {'title': str, 'content': str or list}
            filename: Custom filename (optional)
            
        Returns:
            Dictionary with presentation info and file path
            
        Example:
            >>> doc_gen = DocumentGenerator()
            >>> result = doc_gen.generate_ppt(
            ...     title="My Presentation",
            ...     slides=[
            ...         {'title': 'Introduction', 'content': 'Welcome!'},
            ...         {'title': 'Main Points', 'content': ['Point 1', 'Point 2']}
            ...     ]
            ... )
        """
        if not PPTX_AVAILABLE:
            return self._placeholder_response("PowerPoint", title)
        
        try:
            # Generate filename
            if not filename:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"{title.replace(' ', '_')}_{timestamp}.pptx"
            
            file_path = self.output_dir / filename
            
            # Create presentation
            prs = Presentation()
            prs.slide_width = Inches(10)
            prs.slide_height = Inches(7.5)
            
            # Title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_shape = slide.shapes.title
            subtitle = slide.placeholders[1]
            
            title_shape.text = title
            subtitle.text = f"Generated by Nitro AI\n{datetime.now().strftime('%B %d, %Y')}"
            
            # Content slides
            for slide_data in slides:
                slide_layout = prs.slide_layouts[1]  # Title and Content layout
                slide = prs.slides.add_slide(slide_layout)
                
                # Slide title
                title_shape = slide.shapes.title
                title_shape.text = slide_data.get('title', 'Untitled Slide')
                
                # Slide content
                content = slide_data.get('content', '')
                content_placeholder = slide.placeholders[1]
                text_frame = content_placeholder.text_frame
                text_frame.clear()
                
                # Handle string or list content
                if isinstance(content, list):
                    for item in content:
                        p = text_frame.add_paragraph()
                        p.text = str(item)
                        p.level = 0
                else:
                    p = text_frame.add_paragraph()
                    p.text = str(content)
            
            # Save presentation
            prs.save(str(file_path))
            
            # Track generated document
            doc_info = {
                'type': 'PowerPoint',
                'title': title,
                'filename': filename,
                'file_path': str(file_path),
                'slide_count': len(slides) + 1,  # +1 for title slide
                'size_bytes': file_path.stat().st_size,
                'generated_at': datetime.now().isoformat(),
                'status': 'completed'
            }
            
            self.generated_docs.append(doc_info)
            return doc_info
            
        except Exception as e:
            return {
                'type': 'PowerPoint',
                'title': title,
                'status': 'error',
                'error': str(e),
                'message': 'Failed to generate PowerPoint. Check logs.'
            }
    
    # ========================================================================
    # TEXT DOCUMENT GENERATION
    # ========================================================================
    
    def generate_text(
        self,
        title: str,
        content: str,
        format: str = "txt",
        filename: Optional[str] = None
    ) -> Dict:
        """
        Generate a text document (TXT or Markdown).
        
        Args:
            title: Document title
            content: Main content
            format: 'txt' or 'md' (markdown)
            filename: Custom filename (optional)
            
        Returns:
            Dictionary with document info and file path
        """
        try:
            # Generate filename
            if not filename:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"{title.replace(' ', '_')}_{timestamp}.{format}"
            
            file_path = self.output_dir / filename
            
            # Build document content
            if format == 'md':
                doc_content = f"# {title}\n\n"
                doc_content += f"**Generated by:** Nitro AI\n"
                doc_content += f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
                doc_content += "---\n\n"
                doc_content += content
            else:
                doc_content = f"{title}\n"
                doc_content += "=" * len(title) + "\n\n"
                doc_content += f"Generated by: Nitro AI\n"
                doc_content += f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
                doc_content += "-" * 50 + "\n\n"
                doc_content += content
            
            # Write file
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(doc_content)
            
            # Track generated document
            doc_info = {
                'type': f'Text ({format.upper()})',
                'title': title,
                'filename': filename,
                'file_path': str(file_path),
                'size_bytes': file_path.stat().st_size,
                'generated_at': datetime.now().isoformat(),
                'status': 'completed'
            }
            
            self.generated_docs.append(doc_info)
            return doc_info
            
        except Exception as e:
            return {
                'type': f'Text ({format.upper()})',
                'title': title,
                'status': 'error',
                'error': str(e),
                'message': 'Failed to generate text document.'
            }
    
    # ========================================================================
    # DOCUMENT MANAGEMENT
    # ========================================================================
    
    def list_documents(self, limit: int = 20) -> List[Dict]:
        """
        List recently generated documents.
        
        Args:
            limit: Maximum number of documents to return
            
        Returns:
            List of document information dictionaries
        """
        return self.generated_docs[-limit:]
    
    def get_document(self, filename: str) -> Optional[Path]:
        """
        Get path to a generated document.
        
        Args:
            filename: Document filename
            
        Returns:
            Path object or None if not found
        """
        file_path = self.output_dir / filename
        return file_path if file_path.exists() else None
    
    def _placeholder_response(self, doc_type: str, title: str) -> Dict:
        """Generate placeholder response when libraries not available."""
        return {
            'type': doc_type,
            'title': title,
            'status': 'placeholder',
            'message': f'{doc_type} generation not available. Install required library.',
            'install_command': 'pip install reportlab python-pptx' if doc_type == 'PDF' else 'pip install python-pptx',
            'generated_at': datetime.now().isoformat()
        }


# ============================================================================
# TEMPLATE SYSTEM (Future Enhancement)
# ============================================================================

class DocumentTemplate:
    """
    Document templates for common use cases.
    
    FUTURE: Add more templates
    - Business reports
    - Meeting minutes
    - Project proposals
    - Research papers
    """
    
    @staticmethod
    def business_report_template() -> Dict:
        """Template for business reports."""
        return {
            'title': 'Business Report',
            'sections': [
                'Executive Summary',
                'Introduction',
                'Analysis',
                'Findings',
                'Recommendations',
                'Conclusion'
            ]
        }
    
    @staticmethod
    def presentation_template() -> List[Dict]:
        """Template for presentations."""
        return [
            {'title': 'Introduction', 'content': 'Overview of the topic'},
            {'title': 'Problem Statement', 'content': ['Issue 1', 'Issue 2', 'Issue 3']},
            {'title': 'Solution', 'content': 'Proposed approach'},
            {'title': 'Implementation', 'content': ['Step 1', 'Step 2', 'Step 3']},
            {'title': 'Conclusion', 'content': 'Summary and next steps'}
        ]


# Usage Examples (for developers):
# =================================

if __name__ == "__main__":
    # Example 1: Generate PDF
    doc_gen = DocumentGenerator()
    
    print("Document Generation Examples:")
    print("-" * 60)
    
    # PDF Report
    pdf_result = doc_gen.generate_pdf(
        title="Quarterly Report",
        content="""This is an executive summary.

The company has achieved significant growth this quarter.

Key metrics include:
- Revenue increased by 25%
- Customer satisfaction at 95%
- Market share expanded to 12%

Recommendations for next quarter:
1. Increase marketing budget
2. Hire additional staff
3. Expand product line

Conclusion: Strong performance overall.""",
        author="Business Team"
    )
    
    print(f"PDF Generated: {pdf_result.get('file_path', 'N/A')}")
    print()
    
    # PowerPoint Presentation
    ppt_result = doc_gen.generate_ppt(
        title="Project Proposal",
        slides=[
            {'title': 'Introduction', 'content': 'Welcome to our project proposal'},
            {'title': 'Objectives', 'content': ['Increase efficiency', 'Reduce costs', 'Improve quality']},
            {'title': 'Timeline', 'content': 'Project will take 6 months'},
            {'title': 'Budget', 'content': 'Total investment: $50,000'},
            {'title': 'Next Steps', 'content': ['Approve proposal', 'Assign team', 'Begin development']}
        ]
    )
    
    print(f"PowerPoint Generated: {ppt_result.get('file_path', 'N/A')}")
    print()
    
    # Text Document
    text_result = doc_gen.generate_text(
        title="Meeting Notes",
        content="""Attendees: John, Sarah, Mike

Discussion points:
- New feature development
- Bug fixes priority
- Team expansion

Action items:
- John: Create design mockups
- Sarah: Review budget
- Mike: Hire new developer

Next meeting: Next Monday""",
        format="md"
    )
    
    print(f"Text Document Generated: {text_result.get('file_path', 'N/A')}")
    print()
    
    # List all documents
    print("Recent Documents:")
    for doc in doc_gen.list_documents():
        print(f"  - {doc['title']} ({doc['type']}) - {doc.get('size_bytes', 0)} bytes")
